"""
Visualizations Router

Serves the 7 IEEE-publication-quality PNG plots generated by the ML pipeline.
Returns a structured array (not a flat dict) so the frontend can iterate directly.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from backend.services.pipeline_runner import get_cached
from ml_engine.config import PLOTS_DIR

router = APIRouter(prefix="/visualizations", tags=["Visualizations"])

_PLOT_META = {
    "roc_curves":        {"label": "ROC Curves — Attacker Performance",           "category": "audit"},
    "leakage_bars":      {"label": "Leakage Bar Chart — Per-Attribute AUC",        "category": "audit"},
    "leakage_radar":     {"label": "Leakage Radar — Multi-Attribute Profile",      "category": "audit"},
    "tradeoff_curves":   {"label": "Utility–Privacy Pareto Frontier",              "category": "mitigation"},
    "before_after":      {"label": "Before vs. After Mitigation",                  "category": "mitigation"},
    "training_history":  {"label": "Adversarial Training Loss Curves",             "category": "mitigation"},
    "fairness_disparity":{"label": "Fairness Disparity by Demographic Group",      "category": "fairness"},
}


@router.get("")
@router.get("/")
def list_visualizations():
    """
    List all available plot files as an array of objects with URL fields.

    Returns
    -------
    {status, plots: [{name, filename, url, label, category}], count}
    """
    plots_dict: dict = dict(get_cached("plots") or {})

    # Merge with disk scan so plots appear immediately after generation
    if PLOTS_DIR.exists():
        for p in PLOTS_DIR.glob("*.png"):
            if p.stem not in plots_dict:
                plots_dict[p.stem] = p.name

    plots_array = [
        {
            "name":     name,
            "filename": filename,
            "url":      f"/static/plots/{filename}",
            "label":    _PLOT_META.get(name, {}).get("label", name.replace("_", " ").title()),
            "category": _PLOT_META.get(name, {}).get("category", "general"),
        }
        for name, filename in plots_dict.items()
    ]

    # Stable ordering: audit → mitigation → fairness → rest
    order = list(_PLOT_META.keys())
    plots_array.sort(key=lambda p: order.index(p["name"]) if p["name"] in order else 999)

    return {"status": "ok", "plots": plots_array, "count": len(plots_array)}


@router.get("/{plot_name}")
def get_plot(plot_name: str):
    """Serve a specific plot PNG by name (with or without .png extension)."""
    plot_name = plot_name.replace("..", "").strip("/\\")
    if not plot_name.endswith(".png"):
        plot_name += ".png"

    path = PLOTS_DIR / plot_name
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Plot '{plot_name}' not found. Run the pipeline first.",
        )

    return FileResponse(
        str(path),
        media_type="image/png",
        headers={"Cache-Control": "max-age=3600"},
    )
