import React, { useEffect, useState } from 'react';
import axios from 'axios';

const API = 'http://127.0.0.1:8000';

const PLOT_LABELS = {
  roc_curves:       'ROC Curves — Attacker Performance',
  leakage_bars:     'Leakage Bar Chart — Per-Attribute AUC',
  leakage_radar:    'Leakage Radar — Multi-Attribute Profile',
  tradeoff_curves:  'Utility–Privacy Pareto Frontier',
  before_after:     'Before vs. After Mitigation',
  training_history: 'Adversarial Training History',
  fairness_disparity:'Fairness Disparity by Attribute',
};

export default function VisualizationsPage() {
  const [plots,     setPlots]     = useState([]);
  const [lightbox,  setLightbox]  = useState(null);
  const [loading,   setLoading]   = useState(true);

  useEffect(() => {
    axios.get(`${API}/visualizations`).then(r => {
      const raw = r.data?.plots || r.data || [];
      setPlots(Array.isArray(raw) ? raw : []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  const visible = plots.filter(p => p?.url && !p.url.includes('undefined'));

  return (
    <div className="fade-in">
      {/* ── Topbar ─────────────────────── */}
      <div className="topbar">
        <div className="topbar-breadcrumb">Privacy Framework › <strong>Visualizations</strong></div>
        <div className="topbar-right">
          <span className="topbar-badge">{visible.length} Plots Available</span>
          <span className="topbar-badge">IEEE Publication Quality</span>
        </div>
      </div>

      <div className="page-content">
        <div className="page-header" style={{ marginTop: 8 }}>
          <div className="module-badge" style={{ background: '#fdf4ff', color: '#7e22ce', border: '1px solid #e9d5ff' }}>VISUALIZATIONS</div>
          <h1 className="page-title">Research Visualizations Gallery</h1>
          <p className="page-subtitle">IEEE-publication-quality figures generated by the ML pipeline. Click any plot to enlarge.</p>
        </div>

        {loading && (
          <div className="card">
            <div className="empty-state">
              <div className="empty-state-icon">🔄</div>
              <h3>Loading plots…</h3>
            </div>
          </div>
        )}

        {!loading && visible.length === 0 && (
          <div className="card">
            <div className="empty-state">
              <div className="empty-state-icon">📊</div>
              <h3>No Plots Yet</h3>
              <p>Run the pipeline from the Overview Dashboard to generate visualizations.</p>
            </div>
          </div>
        )}

        {visible.length > 0 && (
          <div className="plot-grid">
            {visible.map((p, i) => {
              const key  = p.name || p.url?.split('/').pop()?.replace('.png','') || i;
              const url  = p.url?.startsWith('http') ? p.url : `${API}${p.url}`;
              const label = PLOT_LABELS[key] || key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
              return (
                <div key={i} className="plot-card" onClick={() => setLightbox(url)} id={`plot-${i}`}>
                  <img src={url} alt={label} loading="lazy" onError={e => { e.target.style.display='none'; }} />
                  <div className="plot-card-label">📊 {label}</div>
                </div>
              );
            })}
          </div>
        )}

        {/* ── Caption guide ─────────────────── */}
        {visible.length > 0 && (
          <div className="card card-padded" style={{ marginTop: 20, background: '#fdf4ff', borderColor: '#e9d5ff' }}>
            <div className="section-label" style={{ color: '#7e22ce' }}>Plot Reference Guide</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3px 24px', fontSize: 12.5, color: '#475569', lineHeight: 1.8 }}>
              <div>📈 <strong>ROC Curves</strong> — Attacker (LR + MLP) per attribute</div>
              <div>📊 <strong>Leakage Bars</strong> — AUC comparison across attributes</div>
              <div>🕸️ <strong>Radar Chart</strong> — Multi-attribute leakage profile</div>
              <div>📉 <strong>Trade-off Curves</strong> — Privacy vs. utility Pareto frontier</div>
              <div>⚖️ <strong>Before/After</strong> — Mitigation effectiveness by attribute</div>
              <div>📓 <strong>Training History</strong> — Adversarial loss convergence</div>
              <div>🧮 <strong>Fairness Disparity</strong> — MDD by demographic group</div>
            </div>
          </div>
        )}
      </div>

      {/* ── Lightbox ─────────────────── */}
      {lightbox && (
        <div className="lightbox" onClick={() => setLightbox(null)}>
          <img src={lightbox} alt="Full size plot" />
        </div>
      )}
    </div>
  );
}
